services:
  - type: web
    name: bottels-app
    env: node
    plan: free
    rootDir: .
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false
      - key: GOOGLE_SHEETS_ID
        sync: false
      - key: GOOGLE_SERVICE_ACCOUNT_JSON
        sync: false
      - key: GOOGLE_CREDENTIALS_PATH
        sync: false
